name: apple_store
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-134.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    

  fonts:
    - family: FuturaMdBT
      fonts:
        - asset: assets/fonts/futuramdbtrusbyme_bold.otf
          weight: 700
        - asset: assets/fonts/futuramdbtrusbyme_medium.otf
          weight: 500

    # - family: Qanelas
    #   fonts:
    #     - asset: assets/fonts/qanelas/Qanelas-Black.ttf
    #       weight: 900
    #     - asset: assets/fonts/qanelas/Qanelas-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/qanelas/Qanelas-ExtraBold.ttf
    #       weight: 800
    #     - asset: assets/fonts/qanelas/Qanelas-Heavy.ttf
    #     - asset: assets/fonts/qanelas/Qanelas-Light.ttf
    #       weight: 300
    #     - asset: assets/fonts/qanelas/Qanelas-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/qanelas/Qanelas-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/qanelas/Qanelas-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/qanelas/Qanelas-Thin.ttf
    #       weight: 100
    #     - asset: assets/fonts/qanelas/Qanelas-UltraLight.ttf
    #       weight: 200
    